#!/usr/bin/env bash
# muse-cli installer for macOS and Linux.
#
#   curl -fsSL https://raw.githubusercontent.com/TheBikramLama/muse-cli/main/install.sh | bash
#
# What it does:
#   1. Checks for Python 3.10+
#   2. Downloads muse-cli to ~/.muse-cli (git clone, or tarball if git is missing)
#   3. Creates a virtualenv and installs dependencies (textual)
#   4. Installs a `muse-cli` launcher on your PATH (~/.local/bin)
#   5. Prints next steps (run `muse-cli setup`)
#
# Non-interactive: safe to pipe from curl. Re-running updates an existing install.
# Set MUSE_CLI_DIR to choose a different install location.
set -euo pipefail

REPO_URL="https://github.com/TheBikramLama/muse-cli.git"
TARBALL_URL="https://codeload.github.com/TheBikramLama/muse-cli/tar.gz/refs/heads/main"
INSTALL_DIR="${MUSE_CLI_DIR:-$HOME/.muse-cli}"
BIN_DIR="$HOME/.local/bin"

say()  { printf '  %s\n' "$*"; }
ok()   { printf '  \xE2\x9C\x93 %s\n' "$*"; }
die()  { printf '  \xE2\x9C\x97 %s\n' "$*" >&2; exit 1; }

echo "muse-cli installer"
echo "=================="

# 1. Python 3.10+
if ! command -v python3 >/dev/null 2>&1; then
  die "python3 not found. Install Python 3.10+ from https://www.python.org/downloads/ and re-run."
fi
PYVER="$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
PYMAJ="${PYVER%%.*}"; PYMIN="${PYVER#*.}"
if [ "$PYMAJ" -lt 3 ] || { [ "$PYMAJ" -eq 3 ] && [ "$PYMIN" -lt 10 ]; }; then
  die "Python $PYVER found — muse-cli needs Python 3.10 or newer."
fi
ok "Python $PYVER"

# 2. Fetch the repo
if [ -d "$INSTALL_DIR/.git" ]; then
  say "Updating existing install at $INSTALL_DIR ..."
  git -C "$INSTALL_DIR" pull --ff-only -q || say "(could not fast-forward; keeping current checkout)"
elif [ -d "$INSTALL_DIR/muse_cli" ]; then
  say "Existing install found at $INSTALL_DIR (no git metadata) — refreshing ..."
  rm -rf "$INSTALL_DIR"
  mkdir -p "$INSTALL_DIR"
  if command -v git >/dev/null 2>&1; then
    git clone -q --depth 1 "$REPO_URL" "$INSTALL_DIR"
  else
    curl -fsSL "$TARBALL_URL" | tar -xz -C "$INSTALL_DIR" --strip-components=1
  fi
else
  say "Installing to $INSTALL_DIR ..."
  mkdir -p "$INSTALL_DIR"
  if command -v git >/dev/null 2>&1; then
    git clone -q --depth 1 "$REPO_URL" "$INSTALL_DIR"
  else
    curl -fsSL "$TARBALL_URL" | tar -xz -C "$INSTALL_DIR" --strip-components=1
  fi
fi
ok "muse-cli sources ready"

# 3. Virtualenv + deps
if [ ! -d "$INSTALL_DIR/.venv" ]; then
  say "Creating virtualenv (first run only) ..."
  python3 -m venv "$INSTALL_DIR/.venv" || die "could not create virtualenv"
fi
"$INSTALL_DIR/.venv/bin/pip" install -q -r "$INSTALL_DIR/requirements.txt" \
  || die "pip install failed"
ok "dependencies installed"

# 4. Launcher on PATH
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/muse-cli" <<EOF
#!/usr/bin/env bash
# Generated by the muse-cli installer. Do not edit by hand.
export PYTHONPATH="$INSTALL_DIR:\$PYTHONPATH"
exec "$INSTALL_DIR/.venv/bin/python" -m muse_cli "\$@"
EOF
chmod +x "$BIN_DIR/muse-cli"
ok "launcher installed at $BIN_DIR/muse-cli"

# 5. PATH check
if ! command -v muse-cli >/dev/null 2>&1; then
  echo ""
  say "NOTE: $BIN_DIR is not on your PATH yet."
  say "Add this line to your ~/.bashrc, ~/.zshrc, or ~/.profile:"
  echo ""
  echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
  echo ""
  say "Then restart your terminal (or run the export now) and continue below."
fi

echo ""
echo "  Done. Next steps:"
echo "    1. muse-cli setup     # one-time pairing with the Muse app"
echo "    2. muse-cli           # launch the TUI"
echo "    3. muse-cli doctor    # check the connection any time"
